<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cad.Geometry\Cad.Geometry.csproj" />
    <ProjectReference Include="..\Cad.Document\Cad.Document.csproj" />
    <ProjectReference Include="..\Cad.Rendering\Cad.Rendering.csproj" />
  </ItemGroup>
</Project>
